### PR TITLE
Add some links to the Julia page

### PR DESCRIPTION
**Pull request by asinghvi17**
Just adds links to the rendered website and Github repo.

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]
Sounds good, look forward to taking a read and running some code!

**Comment by asinghvi17** [comment]
The current build still needs some custom versions of packages to be runnable, hopefully we can iron those issues out in the next week or so!

**Comment by Robinlovelace** [comment]
Great work on this :pray:

**Comment by Robinlovelace** [comment]
Also see https://github.com/geocompx/docker/issues/69, we should add Julia to geocompx/docker also.

**Pull request merged**
