### PR TITLE
add tmap book + spatail data science

### PR DESCRIPTION
**Pull request by defuneste**
just a test adding books, should we go deeper into description ?

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]

**Comment by Robinlovelace** [comment]
Looks good to me. Great to see the Netlify previews, that's new right? Thanks @Nowosad if so!

**Comment by defuneste** [comment]
yup it looks new, I have not explore it too much, but it is an improvement when it drops into your email! I should try to PR something with an error and see what kind of email I get :smile_cat:

**Comment by Nowosad** [comment]
Hi @defuneste, can you add these links on the https://geocompx.org/r.html page rather than in the guestbook? 
For example, as a new "Other recommended resources" below "Vignettes"?

**Comment by defuneste** [comment]
yes will do that tonight!

**Comment by Nowosad** [comment]
Thanks!

**Pull request merged**
