### PR TITLE
Add Julia book cover

### PR DESCRIPTION
**Pull request by evetion**
Fixes https://github.com/geocompx/geocompjl/issues/11 for now.

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]
Nice, and of course made with reproducible Julia code I assume!

**Comment by evetion** [comment]
> Nice, and of course made with reproducible Julia code I assume!

Not (completely) yet. I used Illustrator (shame on me), but the graphic is done in Julia (with the source in the linked PR).

**Comment by Robinlovelace** [comment]
> > Nice, and of course made with reproducible Julia code I assume!
> 
> Not (completely) yet 😰. I used Illustrator (shame on me), but the graphic is done in Julia (with the source in the linked PR).

Don't worry. geocompy is not based on reproducible Python code and it looks great, as does yours, and that's the main thing :+1:

**Comment by Nowosad** [comment]
Thanks, @evetion

**Pull request merged**
