### PR TITLE
Get draft post working, no renv

### PR DESCRIPTION
**Pull request by Robinlovelace**
Heads-up @Nowosad happy to keep the renv but needed to delete to get the website working..

### CODE REVIEW

**Comment by Nowosad** [comment]
Hi @Robinlovelace -- yep, I need to look how to do renv + website rebuilding the most efficient. I will try to find some time to do so in the upcoming week.

**Comment by Robinlovelace** [comment]
Updating all packages to latest versions and not relying on a specific R version would be my main request, so you don't need multiple R versions to reproduce the website.

**Comment by Nowosad** [comment]
@Robinlovelace please read this -- https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html#make-posts-robust-with-renv. I think this inspired me to add renv to our blog. 

We could do one of two things: 1. drop renv entirely or 2. add some instruction to the website readme on how to deal with renv when writing blogposts... What do you think?

**Comment by Robinlovelace** [comment]
@Nowosad I've taken a read. I'm not convinced by this. Definitely not in favour of forcing people to install specific versions of R or outdated packages to contribute. `renv` per post sounds like overkill. Given that code in old posts do not run by default 1. gets my vote.

**Comment by Nowosad** [comment]
@Robinlovelace I am fine with option 1. Feel free to remove renv and merge PR

**Comment by Robinlovelace** [comment]
Awesome. We can always re-add it.

**Comment by Robinlovelace** [comment]
Jakub, for what it's worth, I tested out the latest version and it's fine with the current settings of `renv`: https://github.com/geocompx/geocompx.org/pull/13

**Pull request merged**
