### PR TITLE
Add competition

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad deploy preview not working? https://deploy-preview-15--inquisitive-dragon-b0bcdd.netlify.app/

**Comment by Nowosad** [comment]
@Robinlovelace I never setup deploy previews, so I have no idea... Currently, our website workflow is:
1. You render locally
2. You push to main
3. GHA starts, and renders the website to the gh-pages branch
4. Netlify makes the new version of the website available.

**Comment by Nowosad** [comment]
If you just want to show a blog post without making it on the website, you can change `draft: true` and push to the main. Then the post website will be online, but invisible for people without the url. (e.g., see my future blog post from my website: https://jakubnowosad.com/posts/2023-12-17-spatialising-bp1/)

**Comment by Nowosad** [comment]
Seeing your today's email, I also thought about writing such a blog post --- great work @Robinlovelace! I will review it and reedit either today or in the next few days.

**Comment by Nowosad** [comment]
@Robinlovelace I just added new version of the blog post -- https://github.com/geocompx/geocompx.org/pull/15/commits/a8762466a2e8f7e4d94689740809ff0edd5d42a2.

Feel free to updates the dates: (a) of publishing of the blog post, and (b) of the deadline.

**Review by Robinlovelace — COMMENTED** [review]
Solid set of changes.

**Comment by Robinlovelace** [comment]
Merging, let's see how it looks!

Couple of additional thoughts: @jannes-m do you want to add a link where people can find you? And do my additional commits above seem OK? Looking forward to seeing submissions!

**Comment by Robinlovelace** [comment]
Cool, it's there! https://geocompx.org/post/2023/map-cover-competition/

**Comment by Nowosad** [comment]
The idea of starting that at the beginning of the month is great.

To publish it, you need to change `draft: false`, rerender the website, and then push to GH. Of course, these steps should be done on Friday.

**Comment by Robinlovelace** [comment]
> The idea of starting that at the beginning of the month is great.
> 
> To publish it, you need to change `draft: false`, rerender the website, and then push to GH. Of course, these steps should be done on Friday.

:+1:

**Pull request merged**
